AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  APIStageV1:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1

  Ping:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: dist/ping
      Events:
        Get:
          Type: Api
          Properties:
            Path: /ping
            Method: get
            RestApiId: !Ref APIStageV1
        Post:
          Type: Api
          Properties:
            Path: /ping
            Method: post
            RestApiId: !Ref APIStageV1

  SRD:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: dist/srd
      Events:
        Get:
          Type: Api
          Properties:
            Path: /srd
            Method: post
            RestApiId: !Ref APIStageV1
            
# The echo endpoints displays a lot of info including things such as AWS account number.
# We really only want it enabled for debuggering.
# Echo:
#   Type: AWS::Serverless::Function
#   Properties:
#     Runtime: go1.x
#     Handler: dist/echo
#     Events:
#       Get:
#         Type: Api
#         Properties:
#           Path: /echo
#           Method: get
#           RestApiId: !Ref APIStageV1
#       Post:
#         Type: Api
#         Properties:
#           Path: /echo
#           Method: post
#           RestApiId: !Ref APIStageV1

#Outputs:
#  Endpoint:
#    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

