AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  APIStageV1:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1

  Ping:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: dist/ping
      Events:
        Get:
          Type: Api
          Properties:
            Path: /ping
            Method: get
            RestApiId: !Ref APIStageV1
        Post:
          Type: Api
          Properties:
            Path: /ping
            Method: post
            RestApiId: !Ref APIStageV1
  Spells:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: dist/spells
      Events:
        Get:
          Type: Api
          Properties:
            Path: /spells
            Method: get
            RestApiId: !Ref APIStageV1


#Outputs:
#  Endpoint:
#    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

